spring.application.name=pokemon-tcg-api

# Banco em Memoria H2
spring.datasource.url=jdbc:h2:mem:pokemondb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.show-sql=false
# create-drop recria o schema a cada restart (ideal em desenvolvimento)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Console do H2 (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Springdoc / Swagger (http://localhost:8080/swagger-ui.html)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# API Externa TCGdex (endpoint oficial em ingles)
tcgdex.api.base-url=https://api.tcgdex.net/v2/en

server.port=${PORT:8080}
